### ISSUE TITLE
Failed to create 2 store objects in the DB for 2 expiration objects

### ISSUE THREAD

**Issue by NoamPaz** [GoogleChrome/workbox#1175]
**Library Affected**:
workbox 3.0.0-alpha.4

**Browser & Platform**:
Version 63.0.3239.108 (Official Build) (64-bit) - PC

**Issue Description**:
I create 2 expiration object on 2 different cache names, one for the assets routing and one for GET rest API routing.

```
const assetsExpirationManager = new workbox.expiration.CacheExpiration(
	`${prefix}-${runtime}-${suffix}`,
	{
		maxAgeSeconds: 60 * 60
	}
);

const getExpirationManager = new workbox.expiration.CacheExpiration(
	`${prefix}-api-GET-${suffix}`,
	{
		maxAgeSeconds: 60 * 60
	}
);
```

In the assets routing I use both updateTimestamp, expireEntries function of the assetsExpirationManager instance, and in the GET routing I use the function of the getExpirationManager instance.

The error I get in the console is:
```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at result (https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.4/workbox-core.dev.js:1306:32)
    at new Promise (<anonymous>)
    at https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.4/workbox-core.dev.js:1305:28
    at Generator.next (<anonymous>)
    at step (https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.4/workbox-core.dev.js:14:32)
    at https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.4/workbox-core.dev.js:25:15
    at <anonymous>
```
In the devtools I see only one store object has created (randomly between the 2 cache names) under the workbox-cache-expiration DB.

**Comment by gauntface** [comment]
I'm a bit confused about the code that causes the issue - it it just the code snippet above that causes the error - or is it a route that causes the problem?

A minimal example would be helpful.

Also there is an alpha ending in `.5` that is published now that has some expiration fixes.

**Comment by NoamPaz** [comment]
It still happens on alpha.5.
Here is an example code that causes this issue.
```
const runtimeExpirationManager1 = new workbox.expiration.CacheExpiration(
	'cache1',
	{
		maxAgeSeconds: 60 * 60
	}
);

const runtimeExpirationManager2 = new workbox.expiration.CacheExpiration(
	'cache2',
	{
		maxAgeSeconds: 60 * 60
	}
);

workbox.routing.registerRoute(
	({ url }) => {
		if (url.origin === location.origin) {
			return false;
		}
		return (/^(http(s)?:)?\/\/(?!(api\.|int\.pa\.)).*(t2k|timetoknow)+.*/).test(url.href);
	},
	workbox.strategies.networkFirst({
		cacheName: 'cache1',
		plugins: [
			{
				cacheDidUpdate: async ({ request }) => {
					await runtimeExpirationManager1.updateTimestamp(request.url);
					await runtimeExpirationManager1.expireEntries();
				}
			}
		]
	})
);

workbox.routing.registerRoute(
	({ url }) => {
		if (!(/^(http(s)?:)?\/\/(api\.|int\.pa\.).*/).test(url.href)) {
			return false;
		}
		if ((/.*websocket.*/).test(url.href)) {
			return false;
		}
		return true;
	},
	workbox.strategies.networkFirst({
		cacheName: 'cache2',
		plugins: [
			{
				cacheDidUpdate: async ({ request }) => {
					await runtimeExpirationManager2.updateTimestamp(request.url);
					await runtimeExpirationManager2.expireEntries();
				}
			}
		]
	})
);
```
It happens after executing of both cacheDidUpdate functions in the above code at least one time each.

**Comment by gauntface** [comment]
Thanks for the extra info - I was able to reproduce it - will look into the issue now.
