### ISSUE TITLE
Workbox CLI - Run generateSW,and it doesn't auto-detect default config file.

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1238]
Would be nice if the default config file was picked up
```
╭─matt@matt-XPS ~/Projects/Code/your-excluside-build  ‹master*› 
╰─$ workbox generateSW

Path must be a string. Received {}
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1181:7)
    at _callee$ (/home/matt/Projects/Code/workbox/packages/workbox-cli/build/app.js:77:31)
```

**Comment by jeffposnick** [comment]
Bah, this was a regression from when I started passing through flags like `--injectManifest` through from the CLI.

I'll get it sorted.
