### ISSUE TITLE
Provide additional context in joi-generated validation errors, if possible

### ISSUE THREAD

**Issue by moimael** [GoogleChrome/workbox#1262]
**Library Affected**:
*workbox-webpack-plugin@v3.0.0-alpha.6*

**Browser & Platform**:
*webpack*

**Issue or Feature Request Description**:
Using the latest alpha of the webpack plugin i get the error above. The doc state that it takes a RegExp or null, not an object, am i doing something wrong ?

```

3:16:12 PM: ValidationError: child "dontCacheBustUrlsMatching" fails because ["dontCacheBustUrlsMatching" must be an object]
3:16:12 PM:     at Object.exports.process (/opt/build/repo/node_modules/joi/lib/errors.js:190:19)
3:16:12 PM:     at internals.Object._validateWithOptions (/opt/build/repo/node_modules/joi/lib/types/any/index.js:668:31)
3:16:12 PM:     at internals.Object.validate (/opt/build/repo/node_modules/joi/lib/types/any/index.js:702:21)
3:16:12 PM:     at module.exports (/opt/build/repo/node_modules/workbox-build/build/entry-points/options/validate.js:20:33)
3:16:12 PM:     at _callee$ (/opt/build/repo/node_modules/workbox-build/build/entry-points/generate-sw-string.js:33:23)
3:16:12 PM:     at tryCatch (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:62:40)
3:16:12 PM:     at Generator.invoke [as _invoke] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:296:22)
3:16:12 PM:     at Generator.prototype.(anonymous function) [as next] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:114:21)
3:16:12 PM:     at step (/opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
3:16:12 PM:     at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
3:16:12 PM:     at new Promise (<anonymous>)
3:16:12 PM:     at new F (/opt/build/repo/node_modules/core-js/library/modules/_export.js:35:28)
3:16:12 PM:     at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
3:16:12 PM:     at generateSWString (/opt/build/repo/node_modules/workbox-build/build/entry-points/generate-sw-string.js:53:17)
3:16:12 PM:     at GenerateSW._callee$ (/opt/build/repo/node_modules/workbox-webpack-plugin/build/generate-sw.js:129:24)
3:16:12 PM:     at tryCatch (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:62:40)
3:16:12 PM:     at Generator.invoke [as _invoke] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:296:22)
3:16:12 PM:     at Generator.prototype.(anonymous function) [as next] (/opt/build/repo/node_modules/regenerator-runtime/runtime.js:114:21)
3:16:12 PM:     at step (/opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
3:16:12 PM:     at /opt/build/repo/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
3:16:12 PM:     at <anonymous>
3:16:12 PM: [ { message: '"dontCacheBustUrlsMatching" must be an object',
3:16:12 PM:     path: [ 'dontCacheBustUrlsMatching' ],
3:16:12 PM:     type: 'object.base',
3:16:12 PM:     context:
3:16:12 PM:      { key: 'dontCacheBustUrlsMatching',
3:16:12 PM:        label: 'dontCacheBustUrlsMatching' } } ]
```

**Comment by gauntface** [comment]
@moimael can you provide the config you are using for dontCacheBustUrlsMatching? This will probably help with debugging.

**Comment by moimael** [comment]
Sure, here you go:

```
new GenerateSW({
        globDirectory: 'public/dist',
        globPatterns: [
          '**/manifest.*.js',
          '**/0.*.js',
          '**/vendor.*.js',
          `**/${app}_vendor.*.js`,
          `**/${app}.*.{js,css}`,
          `**/${app}.html`,
          'fonts/*',
        ],
        directoryIndex: 'landing-pages.html',
        swDest: path.join('public/dist', `${app}-service-worker.js`),
        clientsClaim: true,
        skipWaiting: true,
        dontCacheBustUrlsMatching: '/./',
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/res.cloudinary.com\/universal-avenue\/.*\/v1\/commons\/logo_white.svg/,
            handler: 'cacheFirst',
          },
        ],
      })),
```

**Comment by gauntface** [comment]
@moimael this should be a regex, not a string.

So it would end up being: `dontCacheBustUrlsMatching: /./`

@jeffposnick is there anyway we can change the error from `joi` to call out being a RegExp. The message of `must be an object` is misleading, but I can see where it's coming from with `dontCacheBustUrlsMatching: joi.object().type(RegExp),`

**Comment by jeffposnick** [comment]
I'll leave this issue open to see whether there's anything we can do to tell `joi` to throw an error that includes the context about the expected object type.
