### ISSUE TITLE
workbox-precaching integration test needs refactoring

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1299]
**Library Affected**:
*workbox-sw, workbox-build, etc.*

I inadvertently left the `workbox-precaching` integration test out of the refactoring work I did in https://github.com/GoogleChrome/workbox/pull/1284, and it's a little flakey as a result.

**Comment by jeffposnick** [comment]
I realize that this was fixed by #1298.

**Comment by jeffposnick** [comment]
On further inspection, I am still seeing a decent amount of flakiness in [Travis CI](https://travis-ci.org/GoogleChrome/workbox/builds/340009449#L4272) running one of the precaching tests in Firefox Beta:

```sh
[Workbox Log]: Running Integration test on test/workbox-precaching/integration with NODE_ENV 'dev' and browser 'Firefox Beta'
  [workbox-precaching] Precache and Update
    1) should load a page with service worker 
  0 passing (1s)
  1 failing
  1) [workbox-precaching] Precache and Update
       should load a page with service worker :
      AssertionError: expected 4 to equal 3
      + expected - actual
      -4
      +3
      
      at Context.<anonymous> (test/workbox-precaching/integration/precache-and-update.js:87:103)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by jeffposnick** [comment]
Just another data point, in that the same test [sometimes fails](https://travis-ci.org/GoogleChrome/workbox/builds/339950135) on Firefox Stable as well.

That particular failure predates my change in https://github.com/GoogleChrome/workbox/pull/1302—I wanted to clarify that my PR with changes to the `workbox-precaching` module isn't what introduced the flakiness.
