### ISSUE TITLE
workbox-precaching integration test times out in Safari TP 52

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1383]
**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
*[Safari TP 52](https://webkit.org/blog/8165/release-notes-for-safari-technology-preview-52/) on OS X*

https://github.com/GoogleChrome/workbox/blob/master/test/workbox-precaching/integration/precache-and-update.js times out when I run

```sh
gulp test-integration --package='workbox-precaching'
```

(This is not necessarily an issue that was introduced in TP 52, as I don't think I ran the full integration test suite against TP 51.)

There's nothing logged in the JS Console prior to the test timing out:
<img width="800" alt="untitled" src="https://user-images.githubusercontent.com/1749548/37728820-a2deed68-2d11-11e8-9679-15260a01ce6c.png">

**Comment by jeffposnick** [comment]
The message that eventually is logged to the command line is

```sh
[Workbox Log]: Running Integration test on test/workbox-precaching/integration with NODE_ENV 'dev' and browser 'Safari Technology Preview'

  [workbox-precaching] Precache and Update
    1) should load a page with service worker 

  0 passing (4m)
  1 failing

  1) [workbox-precaching] Precache and Update
       should load a page with service worker :
     ScriptTimeoutError: A script did not complete before its timeout expired.
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  From: Task: WebDriver.executeScript()
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at Driver.executeAsyncScript (node_modules/selenium-webdriver/lib/webdriver.js:891:17)
      at module.exports (test/workbox-precaching/utils/getPrecachedIDBData-safari.js:4:37)
      at Context.<anonymous> (test/workbox-precaching/integration/precache-and-update.js:68:30)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

[Workbox Log]: 1 tests failed.

[14:13:00] 'test-integration' errored after 4.7 min
[14:13:00] Error: [Workbox Error Msg] 'gulp test-integration' discovered errors.
    at runIntegrationTestSuite (/Users/jeffy/git/workbox/gulp-tasks/test-integration.js:72:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by jeffposnick** [comment]
It's timing out on

https://github.com/GoogleChrome/workbox/blob/b99d5758c0f3ba349a4ee92c44f34ab692919fdd/test/workbox-precaching/integration/precache-and-update.js#L68

(the `await` never returns).

I gather that this is related to

https://github.com/GoogleChrome/workbox/blob/b99d5758c0f3ba349a4ee92c44f34ab692919fdd/test/workbox-precaching/integration/precache-and-update.js#L37-L39

**Comment by jeffposnick** [comment]
I've been digging into this a bit, and found that https://github.com/GoogleChrome/workbox/blob/49f3d216fe79b2359ff88fb10ca5387dd5cb7bf4/test/workbox-precaching/static/precache-and-update/messenger.js#L18

throws an

```sh
NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
```

That error isn't being caught, which leads to the test hanging rather than reporting anything back.

I'm going to poke around a bit to figure out why the object store doesn't exist at that point in Safari's eyes. If I run similar code manually from within the Safari service worker JS console after stopping the test, I get the results that are expected back, so these IDB entries do in fact end up being written (eventually).
