### ISSUE TITLE
TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by jakemmarsh** [GoogleChrome/workbox#1611]
**Library Affected**:
workbox-webpack-plugin v3.4.1

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:
I'm using the `workbox-webpack-plugin` like so:

```js
new WorkboxPlugin.InjectManifest({
      swSrc: path.resolve(__dirname, 'src', 'app', 'utils', 'service_worker.js'),
      swDest: path.resolve(__dirname, 'static', 'service_worker.js'),
      globDirectory: path.resolve(__dirname, 'src'),
      globIgnores: ['**/*.tsx?'],
      globPatterns: ['**/*.{png,jpg,ico,svg,html,css}']
    })
```

However, when I boot up Webpack I get the following exception:

```
TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at module.exports (/Users/jakemarsh/repos/monolist/web-client/node_modules/workbox-webpack-plugin/build/lib/get-asset-hash.js:28:35)
    at generateMetadataForAssets (/Users/jakemarsh/repos/monolist/web-client/node_modules/workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js:239:15)
    at getManifestEntriesFromCompilation (/Users/jakemarsh/repos/monolist/web-client/node_modules/workbox-webpack-plugin/build/lib/get-manifest-entries-from-compilation.js:317:23)
    at InjectManifest._callee$ (/Users/jakemarsh/repos/monolist/web-client/node_modules/workbox-webpack-plugin/build/inject-manifest.js:143:27)
```

When I added some logging, it seemed to be throwing this error when attempting to process a Typescript definition file. I assumed that would be covered by `globIgnores`? I also tried using just `exclude`. Am I missing something here?

I also ran into the same issue trying to use [next-offline](https://github.com/hanford/next-offline), which uses `GenerateSW` rather than `InjectManifest`.

**Comment by jeffposnick** [comment]
Hello @jakemmarsh!

Taking a step back from your question, the `glob`-related options are [meant](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#cache_additional_non-webpack_assets) to be used when you need to precache assets that exist outside of the webpack asset pipeline. So I wanted to confirm that you actually need to cache non-webpack assets for your web app—if not, you can just leave that out, and that might clear up your issue.

(The [planned revamp](https://github.com/GoogleChrome/workbox/issues/1591#issue-345254577) of the webpack plugin will make this configuration more explicit, as it's unfortunately confusing at the moment.)

If you do need to use the `glob` options to cache non-webpack assets, it would be good to see the full webpack config that you're using, if possible, as well as how you're invoking webpack (using the dev server, for instance, or some other method).
