### ISSUE TITLE
Flaky workbox-google-analytics test

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1751]
**Library Affected**:
*workbox-google-analytics*

I'm seeing periodic flakiness when running the `workbox-google-analytics` integration tests, against either the `prod` or `dev` bundle, in the current Google Chrome Stable (M70).

```sh
1) [workbox-google-analytics] Load and use Google Analytics
       replay failed Google Analytics hits:

      AssertionError: expected [ Array(1) ] to have a length of 2 but got 1
      + expected - actual

      -1
      +2

      at Context.<anonymous> (test/workbox-google-analytics/integration/basic-example.js:125:30)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jeffposnick** [comment]
Phil fixed this in v4.
