### ISSUE TITLE
workbox-broadcast-cache-update demo is not working

### ISSUE THREAD

**Issue by nitinprojects** [GoogleChrome/workbox#1756]
**Browser & Platform**:
*E.g. Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Issue or Feature Request Description**:
workbox-broadcast-cache-update Demo is not working

`[Link]`:
 https://workbox-demos.firebaseapp.com/demo/workbox-broadcast-cache-update/

```**Uncaught WorkboxError: The arguments passed into responsesAreSame() appear to be invalid. Please ensure valid Responses are used.
at responsesAreSame (https://storage.googleapis.com/workbox-cdn/releases/4.0.0-alpha.0/workbox-broadcast-cache-update.dev.js:32:15)
    at BroadcastCacheUpdate.notifyIfUpdated (https://storage.googleapis.com/workbox-cdn/releases/4.0.0-alpha.0/workbox-broadcast-cache-update.dev.js:248:12)
    at self.addEventListener (https://workbox-demos.firebaseapp.com/demo/workbox-broadcast-cache-update/sw.js:25:23)**```

**Comment by jeffposnick** [comment]
The demos have since been rewritten.
