### ISSUE TITLE
Support `urlPattern` in `runtimeCaching` as `function` 

### ISSUE THREAD

**Issue by evilebottnawi** [GoogleChrome/workbox#1764]
**Library Affected**:
- workbox-webpack-plugin
- workbox-build (maybe)

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Allow to use `urlPattern` in `runtimeCaching` as function:
```js
runtimeCaching: [
  {
    handler: "staleWhileRevalidate",
    options: {
      cacheName: "static-resources"
    },
    urlPattern: (context) => {
      // Here complex logic when `RegExp` is not enough
      return true; // or false
    }
  },
]
```

*When reporting bugs, please include relevant JavaScript Console logs and links to public URLs at which the issue could be reproduced.*

**Additions information**
Looks it is already supported in source code https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-routing/_default.mjs#L109

But when i try to use `urlPattern` as function `workbox-webpack-plugin` output me:
```shell
GenerateSWValidationError: child "runtimeCaching" fails because ["runtimeCaching" at position 0 fails because [child "urlPattern" fails because [the value must be a RegExp, "urlPattern" must be a string]]]
    at Object.exports.process (/path/to/node_modules/joi/lib/errors.js:190:19)
    at internals.Object._validateWithOptions (/path/to/node_modules/joi/lib/types/any/index.js:668:31)
    at internals.Object.validate (/path/to/node_modules/joi/lib/types/any/index.js:702:21)
    at module.exports (/path/to/node_modules/workbox-build/build/entry-points/options/validate.js:20:33)
    at _callee$ (/path/to/node_modules/workbox-build/build/entry-points/generate-sw-string.js:36:23)
    at tryCatch (/path/to/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/path/to/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/path/to/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/path/to/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /path/to/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/path/to/node_modules/core-js/library/modules/_export.js:36:28)
    at /path/to/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at generateSWString (/path/to/node_modules/workbox-build/build/entry-points/generate-sw-string.js:63:17)
    at GenerateSW._callee$ (/path/to/node_modules/workbox-webpack-plugin/build/generate-sw.js:155:24)
    at tryCatch (/path/to/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/path/to/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/path/to/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/path/to/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /path/to/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
[ { message: '"urlPattern" must be an object',
    path: [ 'runtimeCaching', 0, 'urlPattern' ],
    type: 'object.base',
    context: { key: 'urlPattern', label: 'urlPattern' } },
  { message: '"urlPattern" must be a string',
    path: [ 'runtimeCaching', 0, 'urlPattern' ],
    type: 'string.base',
    context:
     { value: [Function: urlPattern],
       key: 'urlPattern',
       label: 'urlPattern' } } ]
```

**Comment by jeffposnick** [comment]
Sure thing—this should be straightforward, and can be included as part of v4.
