### ISSUE TITLE
workbox-precaching integration test failures in Chrome Beta

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1806]
**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
*Google Chrome v72*

I initially thought this was limited to the Travis CI environment, but I can reproduce a test failure in Chrome Beta (v72) for the `workbox-precaching` integration suite locally on my Macbook:

```
  1) [workbox-precaching] Precache and Update
       should load a page with service worker :

      AssertionError: expected [ Array(2) ] to have the same members as [ Array(2) ]
      + expected - actual

       [
         "http://localhost:3004/test/workbox-precaching/static/precache-and-update/index.html"
      -  "http://localhost:3004/test/workbox-precaching/static/precache-and-update/styles/index.css"
      +  "http://localhost:3004/test/workbox-precaching/static/precache-and-update/new-request.txt"
       ]

      at Context.<anonymous> (test/workbox-precaching/integration/precache-and-update.js:109:36)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

It doesn't fail on Chrome Stable, so... we need to see whether some of the changes introduced in v72 led to that failure.

**Comment by jeffposnick** [comment]
I'm no longer able to reproduce this failure in Chrome 72 (which is now stable).
