### ISSUE TITLE
Workbox fails to initialize with incorrect cache key

### ISSUE THREAD

**Issue by wallzero** [GoogleChrome/workbox#2153]
**Library Affected**:
`workbox-webpack-plugin@4.3.1`, `GenerateSW`

**Browser & Platform**:
*n/a*

**Issue or Feature Request Description**:

Currently I receive the following browser error with my SPA setup:

```bash
Uncaught incorrect-type: The parameter 'cachedAssetUrl' passed into 'workbox-routing.registerNavigationRoute()' must be of type string.
    at Object.isType (http://localhost:8080/bundle/workbox/workbox-v4.3.1/workbox-core.dev.js:457:13)
    at Object.registerNavigationRoute (http://localhost:8080/bundle/workbox/workbox-v4.3.1/workbox-routing.dev.js:814:25)
    at http://localhost:8080/workbox.js:39:17
```

This is my current setup in `webpack`:

```js
new GenerateSW({
        cacheId: 'any',
        directoryIndex: 'index.html',
        exclude: [/\.map($|\?)/, /\.gz$/],
        importsDirectory: 'workbox',
        importWorkboxFrom: 'local',
        navigateFallback: '/index.html',
        navigateFallbackBlacklist: [/^\/bundle/],
        precacheManifestFilename: 'workbox.manifest.js?[manifestHash]',
        swDest: path.join('..', 'workbox.js')
})
```

The problem is in the generated `workbox.js`:

```js
self.__precacheManifest = [].concat(self.__precacheManifest || []);
workbox.precaching.precacheAndRoute(self.__precacheManifest, {
  "directoryIndex": "/index.html"
});

workbox.routing.registerNavigationRoute(workbox.precaching.getCacheKeyForURL("/index.html"), {
  blacklist: [/^\/bundle/],
});
```

`.getCacheKeyForURL()` is returning `undefined`. The precache key shouldn't have the the leading forward slash. Everything works if I remove it:

```js
workbox.precaching.getCacheKeyForURL("index.html")
```

In searching I noticed the following PR #1874 [which uses `navigateFallback` for the cache key](https://github.com/GoogleChrome/workbox/blob/78a5828f1632aa2beea9affa792be8f7dadde9b4/packages/workbox-build/src/templates/sw-template.js#L51). Perhaps this should instead be using `directoryIndex`?

I also see that [`registerNavigationRoute()` has been deprecated](https://github.com/GoogleChrome/workbox/pull/2143), so perhaps this issue is late and can be ignored. I will test the next `@5.0-alpha` when #2143 is merged.

**Comment by wallzero** [comment]
I've managed to fix the issue by prefixing the applications `<base>` `href` to `navigateFallback`. Now `.getCacheKeyForURL()` finds a match.
