### ISSUE TITLE
workbox-core integration test  failures in Chrome Stable

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2328]
See https://travis-ci.org/GoogleChrome/workbox/builds/636438235#L2429-L2511

```sh
[Workbox]: Running Integration test on test/workbox-core/integration with NODE_ENV 'dev' and browser 'Google Chrome Stable'
  [workbox-core]
1 test failure(s):
Name     :  DBWrapper open times out even in cases where the onblocked handler doesn't file
Message  :  The open request was blocked and timed out
Error    :  Error: The open request was blocked and timed out
    at http://localhost:3004/test/workbox-core/sw/sw-bundle.js:1505:28
3 test failure(s):
Name     :  DBWrapper open throws if blocked for more than the timeout period when openning
Message  :  The open request was blocked and timed out
Error    :  Error: The open request was blocked and timed out
    at http://localhost:3004/test/workbox-core/sw/sw-bundle.js:1505:28
Name     :  DBWrapper open times out even in cases where the onblocked handler doesn't file
Message  :  The open request was blocked and timed out
Error    :  Error: The open request was blocked and timed out
    at http://localhost:3004/test/workbox-core/sw/sw-bundle.js:1505:28
Name     :  DBWrapper getAllMatching accepts options to customize the results returned
Message  :  The open request was blocked and timed out
Error    :  Error: The open request was blocked and timed out
    at http://localhost:3004/test/workbox-core/sw/sw-bundle.js:1505:28
1 test failure(s):
Name     :  DBWrapper open throws if blocked for more than the timeout period when openning
Message  :  The open request was blocked and timed out
Error    :  Error: The open request was blocked and timed out
    at http://localhost:3004/test/workbox-core/sw/sw-bundle.js:1505:28
2 test failure(s):
Name     :  DBWrapper open throws if blocked for more than the timeout period when openning
Message  :  The open request was blocked and timed out
Error    :  Error: The open request was blocked and timed out
    at http://localhost:3004/test/workbox-core/sw/sw-bundle.js:1505:28
Name     :  DBWrapper open times out even in cases where the onblocked handler doesn't file
Message  :  The open request was blocked and timed out
Error    :  Error: The open request was blocked and timed out
    at http://localhost:3004/test/workbox-core/sw/sw-bundle.js:1505:28
2 test failure(s):
Name     :  DBWrapper open throws if blocked for more than the timeout period when openning
Message  :  The open request was blocked and timed out
Error    :  Error: The open request was blocked and timed out
    at http://localhost:3004/test/workbox-core/sw/sw-bundle.js:1505:28
Name     :  DBWrapper open times out even in cases where the onblocked handler doesn't file
Message  :  The open request was blocked and timed out
Error    :  Error: The open request was blocked and timed out
    at http://localhost:3004/test/workbox-core/sw/sw-bundle.js:1505:28
    1) passes all SW unit tests
  [workbox-core] Load core in the browser
    ✓ should load workbox-core in a service worker. (518ms)
  1 passing (58s)
  1 failing
  1) [workbox-core]
       passes all SW unit tests:
     Error: Unit tests failed, see logs above for details
      at runUnitTests (infra/testing/webdriver/runUnitTests.js:36:11)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by jeffposnick** [comment]
(I haven't seen this in quite a while, so closing.)
