### ISSUE TITLE
Fix chromedriver issue with our CI tests

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2443]
```
> chromedriver@80.0.2 install /Users/runner/runners/2.168.0/work/workbox/workbox/node_modules/chromedriver
> node install.js

internal/util.js:214
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at Object.<anonymous> (/Users/runner/runners/2.168.0/work/workbox/workbox/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/runner/runners/2.168.0/work/workbox/workbox/node_modules/chromedriver/install.js:14:20)
```

We currently pull in the latest version of https://www.npmjs.com/package/chromedriver each time we run the macOS CI, instead of pinning to a specific revision. (This is because the version of Chrome we test against changes over time, and the `chromedriver` version is supposed to match the Chrome version.)

It looks like the `chromedriver@80.0.2` install flow is broken. This might be because we're still on node v8 on the macOS CI, and I think downstream dependencies are starting to remove node v8 support.

Workbox v5 still supports node v8, so I want some test coverage still, but I think I can swap our CI config so that our Windows CI uses node v8 and our macOS CI runs a newer node version. Since our Windows CI doesn't install `chromedriver` (it just runs the build tool tests), that might be sufficient.

**Comment by kmcurry** [comment]
I'm getting this same error when pulling/installing chromedriver@85.0.1 via Jenkins Execute Shell
