### ISSUE TITLE
No valid exports main found for workbox

### ISSUE THREAD

**Issue by nish17** [GoogleChrome/workbox#2594]
**Library Affected**:
npm package workbox-cli

**Browser & Platform**:
Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)
node version: v13.6.0
npm version: v6.14.6

**Issue or Feature Request Description**:
Unable to run `workbox wizard`. It throws the following error. Trying to use workbox in the React web app for making it a PWA.

```
➜  $ workbox wizard
internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for '/home/nish/.nvm/versions/node/v13.6.0/lib/node_modules/workbox-cli/node_modules/@rollup/pluginutils'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/nish/.nvm/versions/node/v13.6.0/lib/node_modules/workbox-cli/node_modules/@rollup/plugin-replace/dist/rollup-plugin-replace.cjs.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by jeffposnick** [comment]
I can reproduce that with Node v13.6.0, but not Node v12.18.3 (the current LTS) or Node v14.8.0 (the most recent stable version).

I know that the [odd-numbered versions of Node](https://nodesource.com/blog/understanding-how-node-js-release-lines-work/#evennumberedvsoddnumberednodejsreleases:~:text=Even%2Dnumbered%20vs.%20Odd%2Dnumbered%20Node.js%20Releases) are not as stable, and I have a feeling they switched up some of the way `package.json` exports were interpretted in that specific release.

I'd recommend switching to Node 12.x or Node 14.x.
