### ISSUE TITLE
Webpack 5 Deprecation Warning: SingleEntryPlugin was renamed to EntryPlugin

### ISSUE THREAD

**Issue by lamuertepeluda** [GoogleChrome/workbox#2669]
I am getting this warning since using webpack 5

**Library Affected**:
* workbox-webpack-plugin version 5.1.4

**How to reproduce**:

* webpack 5.4.0
* webpack-cli 4.2.0

`NODE_OPTIONS='--trace-warnings' webpack --config webpack.config.js`

**Output**: 

```
(node:4157) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
    at get SingleEntryPlugin (/home/vito/Development/MyProject/node_modules/webpack/lib/index.js:246:4)
    at Function.SingleEntryPlugin (/home/vito/Development/MyProject/node_modules/webpack/lib/util/memorize.js:22:13)
    at Object.<anonymous> (/home/vito/Development/MyProject/node_modules/workbox-webpack-plugin/build/inject-manifest.js:15:3)
    at Module._compile (/home/vito/Development/MyProject/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/home/vito/Development/MyProject/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/vito/Development/MyProject/node_modules/workbox-webpack-plugin/build/index.js:12:24)
    at Module._compile (/home/vito/Development/MyProject/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/home/vito/Development/MyProject/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
```

**Comment by jeffposnick** [comment]
Please update to `workbox-webpack-plugin` v6.0.0-alpha.3, and let us know how it works for you.

That's the version that introduced `webpack` v5.x support.

Learn more at https://github.com/GoogleChrome/workbox/releases/tag/v6.0.0-alpha.3

**Comment by 0916dhkim** [comment]
@jeffposnick v6 does not produce the deprecation warning. When will it be released?

**Comment by lamuertepeluda** [comment]
I can confirm that v6 alpha works fine for me

**Comment by FloodGames** [comment]
> Please update to `workbox-webpack-plugin` v6.0.0-alpha.3, and let us know how it works for you.
> 
> That's the version that introduced `webpack` v5.x support.
> 
> Learn more at https://github.com/GoogleChrome/workbox/releases/tag/v6.0.0-alpha.3

[webpack-cli] Error: Cannot find module 'levenary'

**Comment by duterte** [comment]
A lot of webpack plugins has deprecation message warning. and I'm sure webpack plugin maintainers can  fix it in the near future.

**Comment by jeffposnick** [comment]
Workbox v6.0.0 is now available.

**Comment by jhenriquevissotto** [comment]
Same problem here!

**Comment by AshutoshMoharana** [comment]
while trying to build using :  npm run build below error is showing, can anyone help me....how to resolve 

npm run build

> pcrf-portal@0.1.0 build
> react-scripts build

(node:17020) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
(Use `node --trace-deprecation ...` to show where the warning was created)
Creating an optimized production build...
Failed to compile.

Cannot read properties of undefined (reading 'includes')
