### ISSUE TITLE
unable to add requests to Queue because of an error

### ISSUE THREAD

**Issue by pavlexander** [GoogleChrome/workbox#3071]
**Library Affected**:
```
    "workbox-background-sync": "^6.5.3",
    "workbox-build": "^6.5.3",
    "workbox-core": "^6.5.3",
    "workbox-precaching": "^6.5.3",
    "workbox-window": "^6.5.3"
```

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
In a service worker I would like to have a reference to a `Queue` object to have a better control of the flow. Users should be able to trigger syncing manually by invoking the `queue.replayRequests();` method (currently sync events automatically occur every 10 minutes or so). Unfortunately enqueueing of requests manually does not seem to work for me. 

The following solution below works, but I don't get to control when sync occurs:

```
import { NetworkOnly } from "workbox-strategies";
import { registerRoute } from "workbox-routing";
import { BackgroundSyncPlugin } from "workbox-background-sync";

const bgSyncPlugin = new BackgroundSyncPlugin("myQueueName", { maxRetentionTime: 24 * 60, });

registerRoute(
  new RegExp(".*/Exercises/.*"),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  "POST"
);
```

But the manual request registration does not work at all

```
import { NetworkOnly } from "workbox-strategies";
import { registerRoute } from "workbox-routing";
import { Queue } from "workbox-background-sync";

const queue = new Queue("myQueueName");

const statusPlugin = {
  fetchDidFail: async ({ originalRequest, request, error, event }) => {
    console.log("fetchDidFail");
    queue._addRequest(originalRequest);
  },
  fetchDidSucceed: ({ response }) => {
    console.log("fetchDidSucceed");
    return response;
  },
};

registerRoute(
  new RegExp(".*/Exercises/.*"),
  new NetworkOnly({
    plugins: [statusPlugin],
  }),
  "POST"
);
```

Upon making a request that fails because of the network error - I can see the `fetchDidFail` message in the logs, but nothing get's added to the queue. Following error gets thrown:

```
Queue.js:222 
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'clone')
    at Ge._addRequest (Queue.js:222:75)
    at Object.fetchDidFail (sw.js? [sm]:48:11)
    at StrategyHandler.js:422:35
    at pe.runCallbacks (StrategyHandler.js:402:19)
    at pe.fetch (StrategyHandler.js:183:28)
    at async ze._handle (NetworkOnly.js:70:24)
    at async ze._getResponse (Strategy.js:144:24)
```

![image](https://user-images.githubusercontent.com/20644772/165801834-38aed55b-ee8e-43f6-9e8d-a96574001189.png)

Is this a bug or do I misuse a workbox API?

A bonus question, that would be nice to hear an anwer to - why does `NetworkOnly` object writes error logs for every failed request? Is it possible to suppress error messages in the log? (unless they are actual code errors and not fetch errors):

![image](https://user-images.githubusercontent.com/20644772/165801805-fb702a8b-c47b-4ada-8aa4-60436a76d180.png)

**Comment by pavlexander** [comment]
I should have read documentation more.
https://developer.chrome.com/docs/workbox/modules/workbox-background-sync/

The answer is to use the `queue.pushRequest({ request: originalRequest });`
Though it would be nice to hear how to get rid of the errors in log..

![image](https://user-images.githubusercontent.com/20644772/165807515-5319afa2-318d-453a-9352-a1e55f0bb282.png)

![image](https://user-images.githubusercontent.com/20644772/165807553-3e66b9eb-2a5b-46f1-ab59-8421b32ec556.png)
