### ISSUE TITLE
workbox-cli :: BackgroundSyncPlugin - Uncaught TypeError: Cannot use 'in' operator to search for 'sync' in undefined

### ISSUE THREAD

**Issue by jcreek** [GoogleChrome/workbox#3097]
**Library Affected**:
workbox-cli, workbox-background-sync

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
The BackgroundSyncPlugin is throwing an error. 

```
Queue.js:341 Uncaught TypeError: Cannot use 'in' operator to search for 'sync' in undefined
    at Queue._addSyncListener (Queue.js:341:1)
    at new Queue (Queue.js:85:1)
    at new BackgroundSyncPlugin (BackgroundSyncPlugin.js:33:1)
    at serviceWorker.js:43:30
```

I installed using `npm install workbox-cli --save-dev` and have version `"workbox-cli": "^6.5.3"` in my devDependencies. I also have `"workbox-webpack-plugin": "^6.5.3"` as a dependency.

My service worker file is as below. This worked a few weeks ago, I made no code changes, but now it no longer works. I initially thought I had not committed a necessary npm file change, but that does not appear to be the case. This can be replicated on multiple machines. 

```js
import * as navigationPreload from 'workbox-navigation-preload';
import { NetworkFirst, NetworkOnly, StaleWhileRevalidate } from 'workbox-strategies';
import { registerRoute, NavigationRoute, Route } from 'workbox-routing';
import { precacheAndRoute } from 'workbox-precaching';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Precache the manifest
precacheAndRoute(self.__WB_MANIFEST);

navigationPreload.enable();

// Cache the offline url and recache it every time it's loaded from cache while online
const offlineRoute = new Route(({ request }) => {
    return request.url.endsWith('/offline') || request.url.endsWith('/offline/')
}, new StaleWhileRevalidate({
    cacheName: 'my-offline'
}));

// Register the route handling the offline page
registerRoute(offlineRoute);

// Create a new navigation route that uses the Network-first, falling back to
// cache strategy for navigation requests with its own cache. This route will be
// handled by navigation preload. The NetworkOnly strategy will work as well.
const navigationRoute = new NavigationRoute(new NetworkFirst({
    cacheName: 'navigations',
    plugins: [
        new ExpirationPlugin({
            maxEntries: 50, // Keep at most 50 entries.
            maxAgeSeconds: 30 * 24 * 60 * 60, // Don't keep any entries for more than 30 days.
            purgeOnQuotaError: true // Automatically cleanup if quota is exceeded.
        })
    ]
}));

// Register the navigation route
registerRoute(navigationRoute);

// Set up a background sync plugin to retry requests made offline once back online
const backgroundSyncPlugin = new BackgroundSyncPlugin('my-offline-requests-queue', {
    maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
});

// Create an online-only route for the offline video view tracking
const backgroundSyncRoute = new Route(({ request }) => {
    return request.url.endsWith('/offline/LogOfflineRequest')
}, new NetworkOnly({
    plugins: [backgroundSyncPlugin]
}));

// Register the background sync route
registerRoute(backgroundSyncRoute);
```

The line the error is throwing at is `const backgroundSyncPlugin = new BackgroundSyncPlugin('my-offline-requests-queue', {`

Any suggestions would be much appreciated.

**Comment by jcreek** [comment]
I found the solution to this myself - the webpack config had a typo so was not excluding my service worker javascript file from being added as a `<script>` tag on the webpage, which meant that code was being run in the wrong scope context, where `self.registration` is not defined. Modifying my webpack build to exclude the js file solved the issue. I hope this helps anyone else who makes the same mistake in the future!
