### ISSUE TITLE
Flakey background-sync Travis Test

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#611]
Example: https://travis-ci.org/GoogleChrome/workbox/jobs/240524215

```
1) Test Runner Environment  should pass 'workbox-background-sync' browser tests in Firefox Nightly:
     Error: 1 test failed.
      at _handleMochaResults (utils/test-runner.js:131:13)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1384:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3092:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3075:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2935:27)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by jeffposnick** [comment]
Beat you to it with #608
